### ISSUE TITLE
No module named 'six'

### ISSUE THREAD

**Issue by jallen-frb** [benkehoe/aws-sso-util#115]
Seems like python core updated...

```
% aws-sso-util --version
Traceback (most recent call last):
  File "/opt/homebrew/bin/aws-sso-util", line 5, in <module>
    from aws_sso_util.cli import cli
  File "/opt/homebrew/Cellar/aws-sso-util/4.32.0_3/libexec/lib/python3.12/site-packages/aws_sso_util/cli.py", line 18, in <module>
    from .assignments import assignments
  File "/opt/homebrew/Cellar/aws-sso-util/4.32.0_3/libexec/lib/python3.12/site-packages/aws_sso_util/assignments.py", line 18, in <module>
    import boto3
  File "/opt/homebrew/Cellar/aws-sso-util/4.32.0_3/libexec/lib/python3.12/site-packages/boto3/__init__.py", line 17, in <module>
    from boto3.session import Session
  File "/opt/homebrew/Cellar/aws-sso-util/4.32.0_3/libexec/lib/python3.12/site-packages/boto3/session.py", line 17, in <module>
    import botocore.session
  File "/opt/homebrew/Cellar/aws-sso-util/4.32.0_3/libexec/lib/python3.12/site-packages/botocore/session.py", line 26, in <module>
    import botocore.client
  File "/opt/homebrew/Cellar/aws-sso-util/4.32.0_3/libexec/lib/python3.12/site-packages/botocore/client.py", line 15, in <module>
    from botocore import waiter, xform_name
  File "/opt/homebrew/Cellar/aws-sso-util/4.32.0_3/libexec/lib/python3.12/site-packages/botocore/waiter.py", line 18, in <module>
    from botocore.docs.docstring import WaiterDocstring
  File "/opt/homebrew/Cellar/aws-sso-util/4.32.0_3/libexec/lib/python3.12/site-packages/botocore/docs/__init__.py", line 15, in <module>
    from botocore.docs.service import ServiceDocumenter
  File "/opt/homebrew/Cellar/aws-sso-util/4.32.0_3/libexec/lib/python3.12/site-packages/botocore/docs/service.py", line 13, in <module>
    from botocore.docs.bcdoc.restdoc import DocumentStructure
  File "/opt/homebrew/Cellar/aws-sso-util/4.32.0_3/libexec/lib/python3.12/site-packages/botocore/docs/bcdoc/restdoc.py", line 17, in <module>
    from botocore.compat import OrderedDict
  File "/opt/homebrew/Cellar/aws-sso-util/4.32.0_3/libexec/lib/python3.12/site-packages/botocore/compat.py", line 31, in <module>
    from dateutil.tz import tzlocal
  File "/opt/homebrew/Cellar/aws-sso-util/4.32.0_3/libexec/lib/python3.12/site-packages/dateutil/tz/__init__.py", line 2, in <module>
    from .tz import *
  File "/opt/homebrew/Cellar/aws-sso-util/4.32.0_3/libexec/lib/python3.12/site-packages/dateutil/tz/tz.py", line 19, in <module>
    import six
ModuleNotFoundError: No module named 'six'
```

**Comment by jallen-frb** [comment]
Fixed with below for those that may need the help:

```
brew uninstall aws-sso-util
brew update && brew upgrade
brew install aws-sso-util
aws-sso-util --version
```
