### ISSUE TITLE
SSL: CERTIFICATE_VERIFY_FAILED] when using aws-sso-util on WSL with Zscaler

### ISSUE THREAD

**Issue by ghost** [benkehoe/aws-sso-util#123]
Aws-sso-util version: 4.33.0
Installation method: pipx
AWS CLI version: 2.17.12 
OS: WSL (on Windows)
Firewall/VPN: Zscaler

Whenever I try to execute command `aws-sso-util login $SSO_START_URL $SSO_REGION` I get error: `Login failed: SSL validation failed for https://oidc.eu-west-1.amazonaws.com/device_authorization [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1006)`

Surprisingly, when using AWS CLI everything works fine: `aws sso login --profile my_profile` does not raise any error. Because of Zscaler, I had to explicitly add file `/usr/local/share/ca-certificates/ZscalerRootCertificate-2048-SHA256.crt` and run `sudo update-ca-certificates -f`(before that AWS CLI was not working either).

I tried to reinstall aws-sso-util but the problem persists. Is there anyway to check which certificates aws-sso-util is using ?
I suspected that the problem could be because of botocore but when I execute `/home/my_user/.local/pipx/venvs/aws-sso-util/bin/python -c "from botocore.session import Session; print(Session().get_config_variable('ca_bundle'))"` the outcome is  `/usr/local/share/ca-certificates/ZscalerRootCertificate-2048-SHA256.crt` which seems fine.

I am also facing a [similar issue](https://github.com/trek10inc/awsume/issues/266) with awsume.

Here is the detailed Traceback:

```
Traceback (most recent call last):
  File "/home/my_user/.local/pipx/venvs/aws-sso-util/lib/python3.11/site-packages/urllib3/connectionpool.py", line 466, in _make_request
    self._validate_conn(conn)
  File "/home/my_user/.local/pipx/venvs/aws-sso-util/lib/python3.11/site-packages/urllib3/connectionpool.py", line 1095, in _validate_conn
    conn.connect()
  File "/home/my_user/.local/pipx/venvs/aws-sso-util/lib/python3.11/site-packages/urllib3/connection.py", line 652, in connect
    sock_and_verified = _ssl_wrap_socket_and_match_hostname(
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/my_user/.local/pipx/venvs/aws-sso-util/lib/python3.11/site-packages/urllib3/connection.py", line 805, in _ssl_wrap_socket_and_match_hostname
    ssl_sock = ssl_wrap_socket(
               ^^^^^^^^^^^^^^^^
  File "/home/my_user/.local/pipx/venvs/aws-sso-util/lib/python3.11/site-packages/urllib3/util/ssl_.py", line 465, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(sock, context, tls_in_tls, server_hostname)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/my_user/.local/pipx/venvs/aws-sso-util/lib/python3.11/site-packages/urllib3/util/ssl_.py", line 509, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/ssl.py", line 517, in wrap_socket
    return self.sslsocket_class._create(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/ssl.py", line 1104, in _create
    self.do_handshake()
  File "/usr/lib/python3.11/ssl.py", line 1382, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1006)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/my_user/.local/pipx/venvs/aws-sso-util/lib/python3.11/site-packages/botocore/httpsession.py", line 464, in send
    urllib_response = conn.urlopen(
                      ^^^^^^^^^^^^^
  File "/home/my_user/.local/pipx/venvs/aws-sso-util/lib/python3.11/site-packages/urllib3/connectionpool.py", line 843, in urlopen
    retries = retries.increment(
              ^^^^^^^^^^^^^^^^^^
  File "/home/my_user/.local/pipx/venvs/aws-sso-util/lib/python3.11/site-packages/urllib3/util/retry.py", line 449, in increment
    raise reraise(type(error), error, _stacktrace)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/my_user/.local/pipx/venvs/aws-sso-util/lib/python3.11/site-packages/urllib3/util/util.py", line 39, in reraise
    raise value
  File "/home/my_user/.local/pipx/venvs/aws-sso-util/lib/python3.11/site-packages/urllib3/connectionpool.py", line 789, in urlopen
    response = self._make_request(
               ^^^^^^^^^^^^^^^^^^^
  File "/home/my_user/.local/pipx/venvs/aws-sso-util/lib/python3.11/site-packages/urllib3/connectionpool.py", line 490, in _make_request
    raise new_e
urllib3.exceptions.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1006)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/my_user/.local/pipx/venvs/aws-sso-util/lib/python3.11/site-packages/aws_sso_util/login.py", line 135, in login
    token = token_fetcher.fetch_token(instance.start_url, force_refresh=force)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/my_user/.local/pipx/venvs/aws-sso-util/lib/python3.11/site-packages/aws_sso_lib/vendored_botocore/utils.py", line 228, in fetch_token
    return self._token(start_url, force_refresh)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/my_user/.local/pipx/venvs/aws-sso-util/lib/python3.11/site-packages/aws_sso_lib/vendored_botocore/utils.py", line 223, in _token
    token = self._poll_for_token(start_url)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/my_user/.local/pipx/venvs/aws-sso-util/lib/python3.11/site-packages/aws_sso_lib/vendored_botocore/utils.py", line 173, in _poll_for_token
    authorization = self._authorize_client(start_url, registration)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/my_user/.local/pipx/venvs/aws-sso-util/lib/python3.11/site-packages/aws_sso_lib/vendored_botocore/utils.py", line 153, in _authorize_client
    response = self._client.start_device_authorization(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/my_user/.local/pipx/venvs/aws-sso-util/lib/python3.11/site-packages/botocore/client.py", line 565, in _api_call
    return self._make_api_call(operation_name, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/my_user/.local/pipx/venvs/aws-sso-util/lib/python3.11/site-packages/botocore/client.py", line 1001, in _make_api_call
    http, parsed_response = self._make_request(
                            ^^^^^^^^^^^^^^^^^^^
  File "/home/my_user/.local/pipx/venvs/aws-sso-util/lib/python3.11/site-packages/botocore/client.py", line 1027, in _make_request
    return self._endpoint.make_request(operation_model, request_dict)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/my_user/.local/pipx/venvs/aws-sso-util/lib/python3.11/site-packages/botocore/endpoint.py", line 119, in make_request
    return self._send_request(request_dict, operation_model)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/my_user/.local/pipx/venvs/aws-sso-util/lib/python3.11/site-packages/botocore/endpoint.py", line 202, in _send_request
    while self._needs_retry(
          ^^^^^^^^^^^^^^^^^^
  File "/home/my_user/.local/pipx/venvs/aws-sso-util/lib/python3.11/site-packages/botocore/endpoint.py", line 354, in _needs_retry
    responses = self._event_emitter.emit(
                ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/my_user/.local/pipx/venvs/aws-sso-util/lib/python3.11/site-packages/botocore/hooks.py", line 412, in emit
    return self._emitter.emit(aliased_event_name, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/my_user/.local/pipx/venvs/aws-sso-util/lib/python3.11/site-packages/botocore/hooks.py", line 256, in emit
    return self._emit(event_name, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/my_user/.local/pipx/venvs/aws-sso-util/lib/python3.11/site-packages/botocore/hooks.py", line 239, in _emit
    response = handler(**kwargs)
               ^^^^^^^^^^^^^^^^^
  File "/home/my_user/.local/pipx/venvs/aws-sso-util/lib/python3.11/site-packages/botocore/retryhandler.py", line 207, in __call__
    if self._checker(**checker_kwargs):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/my_user/.local/pipx/venvs/aws-sso-util/lib/python3.11/site-packages/botocore/retryhandler.py", line 284, in __call__
    should_retry = self._should_retry(
                   ^^^^^^^^^^^^^^^^^^^
  File "/home/my_user/.local/pipx/venvs/aws-sso-util/lib/python3.11/site-packages/botocore/retryhandler.py", line 320, in _should_retry
    return self._checker(attempt_number, response, caught_exception)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/my_user/.local/pipx/venvs/aws-sso-util/lib/python3.11/site-packages/botocore/retryhandler.py", line 363, in __call__
    checker_response = checker(
                       ^^^^^^^^
  File "/home/my_user/.local/pipx/venvs/aws-sso-util/lib/python3.11/site-packages/botocore/retryhandler.py", line 247, in __call__
    return self._check_caught_exception(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/my_user/.local/pipx/venvs/aws-sso-util/lib/python3.11/site-packages/botocore/retryhandler.py", line 416, in _check_caught_exception
    raise caught_exception
  File "/home/my_user/.local/pipx/venvs/aws-sso-util/lib/python3.11/site-packages/botocore/endpoint.py", line 281, in _do_get_response
    http_response = self._send(request)
                    ^^^^^^^^^^^^^^^^^^^
  File "/home/my_user/.local/pipx/venvs/aws-sso-util/lib/python3.11/site-packages/botocore/endpoint.py", line 377, in _send
    return self.http_session.send(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/my_user/.local/pipx/venvs/aws-sso-util/lib/python3.11/site-packages/botocore/httpsession.py", line 491, in send
    raise SSLError(endpoint_url=request.url, error=e)
botocore.exceptions.SSLError: SSL validation failed for https://oidc.eu-west-1.amazonaws.com/device_authorization [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1006)
ERROR:aws_sso_util.login:Login failed: SSL validation failed for https://oidc.eu-west-1.amazonaws.com/device_authorization [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1006)
```

**Comment by ghost** [comment]
I have solved my own problem.
The parameter `default.ca_bundle` was set in `~/.aws/config`:

```

[default]
ca_bundle = /usr/local/share/ca-certificates/ZscalerRootCertificate-2048-SHA256.crt

```
Removing it resolved the issue.
The path is correct and yet it was causing an SSL error with `awsume` and `aws-sso-util`.
For some reasons, this did not cause any issue with AWS CLI.
