### ISSUE TITLE
Error after upgrade

### ISSUE THREAD

**Issue by hoegertn** [benkehoe/aws-sso-util#19]
After upgrading I get the following error:

```
$ aws-sso-util --help
Traceback (most recent call last):
  File "/Users/hoegertn/.local/bin/aws-sso-util", line 5, in <module>
    from aws_sso_util.cli import cli
  File "/Users/hoegertn/.local/pipx/venvs/aws-sso-util/lib/python3.9/site-packages/aws_sso_util/cli.py", line 21, in <module>
    from .credential_process import credential_process
  File "/Users/hoegertn/.local/pipx/venvs/aws-sso-util/lib/python3.9/site-packages/aws_sso_util/credential_process.py", line 30, in <module>
    from aws_sso_lib.sso import get_token_fetcher, get_credentials
ImportError: cannot import name 'get_token_fetcher' from 'aws_sso_lib.sso' (/Users/hoegertn/.local/pipx/venvs/aws-sso-util/lib/python3.9/site-packages/aws_sso_lib/sso.py)
```

Any idea what I need to do?

**Comment by benkehoe** [comment]
I can see exactly why this is breaking, and ~I'm mystified as to why it is working for me~ my script for testing the CLI with new changes in the library was not as clever as I thought it was. Back to `rm -rf .venv && poetry install`.

This is fixed in 3.21, sorry.
