### ISSUE TITLE
CloudFormation macro should handle CloudFormation functions

### ISSUE THREAD

**Issue by jutley** [benkehoe/aws-sso-util#28]
When I use the macro to create a PermissionSet, I often want to define the GroupIds, PermissionSetArns, and Accounts as a reference to a CloudFormation parameter. When I actually try this, however, the macro fails as it is expecting strings for these fields, but the result is a dict instead (something like `{"Ref": "GroupId"}`).

In order to have reusable CFn templates with parameterized details, the macro should be able to support CloudFormation's `Ref` syntax, as well as the other CloudFormation functions.

**Comment by benkehoe** [comment]
I'll take a look, this has been working for me. Can you provide the logs from the macro Lambda? Remember to scrub any account-specific information.

**Comment by jutley** [comment]
Absolutely. Here are the logs:
```
[ERROR]	2021-04-12T19:27:19.544Z	ac5aad9c-1ef2-4782-bed5-f1ed75f2c316	An error occurred: Parameter validation failed:
Invalid type for parameter GroupId, value: {'Ref': 'SSOGroupId'}, type: <class 'dict'>, valid types: <class 'str'>
Traceback (most recent call last):
  File "/var/task/aws_sso_util/cfn_lib/macro.py", line 259, in handler
    template_collection = parent_template.get_templates(
  File "/var/task/aws_sso_util/cfn_lib/templates.py", line 258, in get_templates
    parent_template = self._get_template(
  File "/var/task/aws_sso_util/cfn_lib/templates.py", line 178, in _get_template
    add_assignments_to_template(template, self.assignments,
  File "/var/task/aws_sso_util/cfn_lib/templates.py", line 84, in add_assignments_to_template
    assignment.get_resource(
  File "/var/task/aws_sso_util/cfn_lib/resources.py", line 244, in get_resource
    principal_name = principal_name_fetcher(self.principal.type.value, self.principal.id)
  File "/var/task/aws_sso_util/cfn_lib/utils.py", line 112, in fetcher
    group = lookup.lookup_group_by_id(session, ids, id, cache=cache)
  File "/var/task/aws_sso_lib/lookup.py", line 226, in lookup_group_by_id
    group = identity_store.describe_group(IdentityStoreId=ids.identity_store_id, GroupId=group_id)
  File "/var/task/botocore/client.py", line 357, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/var/task/botocore/client.py", line 648, in _make_api_call
    request_dict = self._convert_to_request_dict(
  File "/var/task/botocore/client.py", line 696, in _convert_to_request_dict
    request_dict = self._serializer.serialize_to_request(
  File "/var/task/botocore/validate.py", line 293, in serialize_to_request
    raise ParamValidationError(report=report.generate_report())
botocore.exceptions.ParamValidationError: Parameter validation failed:
Invalid type for parameter GroupId, value: {'Ref': 'SSOGroupId'}, type: <class 'dict'>, valid types: <class 'str'>
```

The resource looked like this:
```
    "Assignments": {
      "Type": "SSOUtil::SSO::AssignmentGroup",
      "Properties": {
        "InstanceArn": "arn:aws:sso:::instance/ssoins-7900000000000000",
        "Principal": {
          "Type": "GROUP",
          "Id": {"Ref": "SSOGroupId"}
        },
        "PermissionSet": "arn:aws:sso:::permissionSet/ssoins-7900000000000000/ps-0000000000000000",
        "Target": {
          "Type": "AWS_ACCOUNT",
          "Id": "410000000000"
        }
      }
    }
```

**Comment by benkehoe** [comment]
Aha! It's the thing that looks up what the names of the identifiers are, to put them in the generated `AWS::SSO::Assignment` resources. And when it's a reference, there's no resolved value to look up. You can disable the lookup temporarily by changing the `LookupNames` parameter of the macro stack to `false`.

**Comment by jutley** [comment]
Gotcha. Good to know; that makes sense. I'll disable that setting for now!

**Comment by benkehoe** [comment]
Keeping this open until it's properly fixed.

**Comment by benkehoe** [comment]
This [should be fixed](https://github.com/benkehoe/aws-sso-util/commit/36dba8c949bb6c90e193d2a622b0bca1b979cd73#diff-45dd1f975b4354797a240889507d2e86607026c63b0ae1b9d14bf3dd8d063c72) with `aws-sso-util` version 4.23. It was already there for permission sets, just not for principals and targets, for some reason.
