### ISSUE TITLE
Broken profiles when the AWS account name containing `[` and `]`.

### ISSUE THREAD

**Issue by xeres** [benkehoe/aws-sso-util#31]
Thank you for aws-sso-util.

I found  `aws-sso-util configure populate` generates broken profiles when the AWS account name containing `[` and `]`.

If the AWS account name is `[PROD] Project Name`,  `aws-sso-util configure populate`  generates as like as follow:

```ini
[profile [PROD]-Project-Name.AdministratorAccess]
sso_start_url = https://<example>.awsapps.com/start
sso_region = us-east-1
sso_account_name = [PROD] Project Name
sso_account_id = 123456789012
sso_role_name = AdministratorAccess
region = us-east-1
credential_process = aws-sso-util credential-process --profile '[PROD]-Project-Name.AdministratorAccess'
sso_auto_populated = true
```

And `aws-sso-util configure populate` outputs followed error and die.
```shell-session
$ aws-sso-util configure populate --sso-start-url https://<example>.awsapps.com/start --sso-region us-east-1 -r us-east-1
Logging in to https://<example>.awsapps.com/start
Gathering accounts and roles
Writing # profiles to /home/xeres/.aws/config
Traceback (most recent call last):
  File "/home/xeres/.local/share/pipx/venvs/aws-sso-util/lib/python3.8/site-packages/botocore/configloader.py", line 149, in raw_config_parse
    cp.read([path])
  File "/home/xeres/.local/share/pyenv/versions/3.8.8/lib/python3.8/configparser.py", line 697, in read
    self._read(fp, filename)
  File "/home/xeres/.local/share/pyenv/versions/3.8.8/lib/python3.8/configparser.py", line 1067, in _read
    raise DuplicateSectionError(sectname, fpname,
configparser.DuplicateSectionError: While reading from '/home/xeres/.aws/config' [line 582]: section 'profile [MPF' already exists

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/xeres/.local/bin/aws-sso-util", line 8, in <module>
    sys.exit(cli())
  File "/home/xeres/.local/share/pipx/venvs/aws-sso-util/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/xeres/.local/share/pipx/venvs/aws-sso-util/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/xeres/.local/share/pipx/venvs/aws-sso-util/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/xeres/.local/share/pipx/venvs/aws-sso-util/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/xeres/.local/share/pipx/venvs/aws-sso-util/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/xeres/.local/share/pipx/venvs/aws-sso-util/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/xeres/.local/share/pipx/venvs/aws-sso-util/lib/python3.8/site-packages/aws_sso_util/populate_profiles.py", line 359, in populate_profiles
    existing_config = Session(profile=config.profile_name).get_scoped_config()
  File "/home/xeres/.local/share/pipx/venvs/aws-sso-util/lib/python3.8/site-packages/botocore/session.py", line 341, in get_scoped_config
    profile_map = self._build_profile_map()
  File "/home/xeres/.local/share/pipx/venvs/aws-sso-util/lib/python3.8/site-packages/botocore/session.py", line 237, in _build_profile_map
    self._profile_map = self.full_config['profiles']
  File "/home/xeres/.local/share/pipx/venvs/aws-sso-util/lib/python3.8/site-packages/botocore/session.py", line 368, in full_config
    self._config = botocore.configloader.load_config(config_file)
  File "/home/xeres/.local/share/pipx/venvs/aws-sso-util/lib/python3.8/site-packages/botocore/configloader.py", line 106, in load_config
    parsed = raw_config_parse(config_filename)
  File "/home/xeres/.local/share/pipx/venvs/aws-sso-util/lib/python3.8/site-packages/botocore/configloader.py", line 151, in raw_config_parse
    raise botocore.exceptions.ConfigParseError(
botocore.exceptions.ConfigParseError: Unable to parse config file: /home/xeres/.aws/config
```

I think `botocore/configloader` doesn't support profile names containing `[` and `]`.

If the AWS Organizations has **an** AWS account containing `[` and `]`, `aws configure list-profiles` will output followed:
```shell-session
$ aws configure list-profiles
(...skip...)
[PROD
```

If the AWS Organizations has many AWS accounts containing `[` and `]`, `aws configure list-profiles` can't parse the config.
```shell-session
$ aws configure list-profiles

Unable to parse config file: /home/xeres/.aws/config
```

I think that `aws_sso_lib.config_file_writer#process_profile_name()` provides not enogth escaping, but I can't decide how to fix.

How do you think?

My environments:
- Python 3.8.8
- pipx 0.16.2.1
- aws-sso-util 4.24.0
- boto3 1.17.69
- botocore 1.20.69

**Comment by benkehoe** [comment]
Good call. This should be fixed in [v4.25](https://github.com/benkehoe/aws-sso-util/blob/master/CHANGELOG.md#cli-v425)
