### ISSUE TITLE
aws-sso-util configure profile test-profile not working as expected

### ISSUE THREAD

**Issue by cisum-la** [benkehoe/aws-sso-util#7]
On terminal prompt i typed `aws-sso-util configure profile test-profile` to configure test-profile. 
My expectation is it will prompt me for start url, aws region etc. but instead it errors out with below message

`TypeError: configure_profile() got an unexpected keyword argument 'account_id'`

Full error log:
```
Traceback (most recent call last):
  File "/Users/…/.local/bin/aws-sso-util", line 8, in <module>
    sys.exit(cli())
  File "/Users/…/.local/pipx/venvs/aws-sso-util/lib/python3.9/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/Users/…/.local/pipx/venvs/aws-sso-util/lib/python3.9/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/Users/…/.local/pipx/venvs/aws-sso-util/lib/python3.9/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/…/.local/pipx/venvs/aws-sso-util/lib/python3.9/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/…/.local/pipx/venvs/aws-sso-util/lib/python3.9/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/…/.local/pipx/venvs/aws-sso-util/lib/python3.9/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
TypeError: configure_profile() got an unexpected keyword argument 'account_id'

```

The interesting part is that all the rest of the below command seem to work for me, only the above command fails 
`aws-sso-util logout` - Works
`aws-sso-util login` - Works, i see the usual SSO signin process followed by login succeeded and valid until timestamp 
`aws-sso-util configure populate --region region` Works, i see all the profiles getting written to my .aws/config file

Appreciate any help i can get to solve the above issue.

**Comment by benkehoe** [comment]
I botched a git patching somewhere along the way. It's fixed now in v2.10.0

**Comment by cisum-la** [comment]
thanks a lot @benkehoe ! I upgraded to latest v2.10.0 of aws-sso-util and configure command is working as expected for me.

**Comment by benkehoe** [comment]
Thanks for finding this before I officially announced the project 😄
